<?php

/**
 * Implements hook_menu_alter().
 */
function islandora_solr_facetapi_menu_alter(&$items) {
  $items['admin/islandora/search/islandora_solr/facets']['weight'] = 10;
}

/**
 * Implements hook_facetapi_searcher_info().
 */
function islandora_solr_facetapi_facetapi_searcher_info() {
  return array(
    'islandora_solr@searcher' => array(
      'label' => t('Islandora SOLR Search'),
      'adapter' => 'islandora_solr',
      'path' => 'admin/islandora/search/islandora_solr',
      'types' => array('islandora_solr_index'),
      'supports facet missing' => TRUE,
      'supports facet mincount' => TRUE,
      'include default facets' => TRUE,
    ),
  );
}

/**
 * Implements hook_facetapi_facet_info().
 */
function islandora_solr_facetapi_facetapi_facet_info(array $searcher_info) {
  $facets = array();

  // Facets are usually associated with the type of content stored in the index.
  if (isset($searcher_info['types']['islandora_solr_index'])) {

    $luke = islandora_solr_get_luke();
    foreach ($luke['fields'] as $field_name => $field) {

      if ($field['type'] != 'text') {
        $facets[$field_name] = array(
          'name' => $field_name,
          'label' => $field_name,
          'description' => t('Type: @type', array('@type' => $field['type'], '@schema' => $field['schema'])),
          'allowed operators' => array(FACETAPI_OPERATOR_AND => TRUE, FACETAPI_OPERATOR_OR => TRUE),
        );

        switch ($field['type']) {
          case 'string':
            $facets[$field_name]['query types'] = array('term');
            break;
          case 'date':
            $facets[$field_name]['query types'] = array('date', 'date_range');
            break;
        }
      }
    }
  }

  return $facets;
}

/**
 * Implements hook_facetapi_adapters().
 */
function islandora_solr_facetapi_facetapi_adapters() {
  return array(
    'islandora_solr' => array(
      'handler' => array(
        'class' => 'IslandoraSolrFacetapiAdapter',
      ),
    ),
  );
}

/**
 * Implements hook_facetapi_query_types().
 */
function islandora_solr_facetapi_facetapi_facetapi_query_types() {
  return array(
    // 'search_api_term' => array(
    //   'handler' => array(
    //     'class' => 'SearchApiFacetapiTerm',
    //     'adapter' => 'search_api',
    //   ),
    // ),
    // 'search_api_date' => array(
    //   'handler' => array(
    //     'class' => 'SearchApiFacetapiDate',
    //     'adapter' => 'search_api',
    //   ),
    // ),
  );
}
